/*
 * Copyright (c) 2024 Huawei Technologies Co., Ltd.
 * AscendOpCommonLib is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */
#include "../iterator.h"

template <ArchType ArchTag, typename DType> struct gm_to_ub {
    __aicore__ inline gm_to_ub(AscendC::LocalTensor<DType> dstTensor, AscendC::GlobalTensor<DType> srcTensor,
                               uint8_t sid, uint16_t nBurst, uint16_t lenBurst, uint16_t srcStride, uint16_t dstStride)
    {
#ifdef USE_ASCENDC
        AscendC::DataCopy(dstTensor, srcTensor, AscendC::DataCopyParams(nBurst, lenBurst, srcStride, dstStride));
#else
        copy_gm_to_ubuf((__ubuf__ DType *)dstTensor.GetPhyAddr(), (__gm__ DType *)srcTensor.GetPhyAddr(), 0, nBurst,
                        lenBurst, srcStride, dstStride);
#endif
    };
};

template <ArchType ArchTag, typename DType> struct gm_to_ub_align {
    __aicore__ inline gm_to_ub_align(AscendC::LocalTensor<DType> dstTensor, AscendC::GlobalTensor<DType> srcTensor,
                                     uint8_t sid, uint16_t nBurst, uint32_t lenBurst, uint8_t leftPaddingNum,
                                     uint8_t rightPaddingNum, uint32_t srcGap, uint32_t dstGap)
    {
#ifdef USE_ASCENDC
        AscendC::DataCopyPad(dstTensor, srcTensor, AscendC::DataCopyExtParams(nBurst, lenBurst, srcGap, dstGap, 0),
                             AscendC::DataCopyPadExtParams<DType>(false, leftPaddingNum, rightPaddingNum, 0));
#else
        if constexpr (sizeof(DType) == 1) {
            copy_gm_to_ubuf_align_b8((__ubuf__ DType *)dstTensor.GetPhyAddr(), (__gm__ DType *)srcTensor.GetPhyAddr(),
                                     sid, nBurst, lenBurst, leftPaddingNum, rightPaddingNum, srcGap, dstGap);
        } else if constexpr (sizeof(DType) == 2) {
            copy_gm_to_ubuf_align_b16((__ubuf__ DType *)dstTensor.GetPhyAddr(), (__gm__ DType *)srcTensor.GetPhyAddr(),
                                      sid, nBurst, lenBurst, leftPaddingNum, rightPaddingNum, srcGap, dstGap);
        } else if constexpr (sizeof(DType) == 4) {
            copy_gm_to_ubuf_align_b32((__ubuf__ DType *)dstTensor.GetPhyAddr(), (__gm__ DType *)srcTensor.GetPhyAddr(),
                                      sid, nBurst, lenBurst, leftPaddingNum, rightPaddingNum, srcGap, dstGap);
        }
#endif
    };
};

template <ArchType ArchTag, typename DType> struct ub_to_ub {
    __aicore__ inline ub_to_ub(AscendC::LocalTensor<DType> dstTensor, AscendC::LocalTensor<DType> srcTensor,
                               uint8_t sid, uint16_t nBurst, uint16_t lenBurst, uint16_t srcStride, uint16_t dstStride)
    {
        AscendC::DataCopy(dstTensor, srcTensor, AscendC::DataCopyParams(nBurst, lenBurst, srcStride, dstStride));
    };
};

template <ArchType ArchTag, typename DataType, DataFormat InDataFormat = DataFormat::ND,
          DataFormat OutDataFormat = DataFormat::ND>
struct ub_to_gm {
    __aicore__ inline ub_to_gm(AscendC::GlobalTensor<DataType> dstTensor, AscendC::LocalTensor<DataType> srcTensor,
                               uint8_t sid, uint16_t nBurst, uint16_t lenBurst, uint16_t srcStride, uint16_t dstStride)
    {
        AscendC::DataCopy(dstTensor, srcTensor, AscendC::DataCopyParams(nBurst, lenBurst, srcStride, dstStride));
    };
};

template <ArchType ArchTag, typename DataType> struct ub_to_gm<ArchTag, DataType, DataFormat::NZ, DataFormat::NZ> {
    using HardwareParams = HardwareInfo<ArchTag>;
    static constexpr uint32_t BLOCK_SIZE = HardwareParams::l1l0BlockSize / sizeof(DataType);

    __aicore__ ub_to_gm(AscendC::GlobalTensor<DataType> gmTensor, AscendC::LocalTensor<DataType> l1Tensor,
                        uint32_t nTileActual, uint32_t nTileCeil, uint32_t nVal, uint32_t dTileActual,
                        uint32_t dTileCeil, uint32_t dVal)
    {
        uint64_t dstStride = nTileCeil - nTileActual;
        if (dstStride < STRIDE_LIMIT) {
            AscendC::DataCopy(gmTensor, l1Tensor,
                              AscendC::DataCopyParams(dTileActual / BLOCK_SIZE, // nBurst
                                                      nTileActual,              // lenBurst
                                                      0,                        // srcGap
                                                      dstStride));              // dstGap
        } else {
            for (uint64_t i = 0; i < dTileActual / BLOCK_SIZE; i++) {
                uint64_t srcOffset = i * nTileActual * BLOCK_SIZE;
                uint64_t dstOffset = i * nTileCeil * BLOCK_SIZE;
                AscendC::DataCopy(gmTensor[dstOffset], l1Tensor[srcOffset],
                                  AscendC::DataCopyParams(1,           // nBurst
                                                          nTileActual, // lenBurst
                                                          0,           // srcGap
                                                          0));         // dstGap
            }
        }
    };
};

template <ArchType ArchTag, typename DType> struct ub_to_gm_align {
    __aicore__ inline ub_to_gm_align(AscendC::GlobalTensor<DType> dstTensor, AscendC::LocalTensor<DType> srcTensor,
                                     uint8_t sid, uint16_t nBurst, uint32_t lenBurst, uint8_t leftPaddingNum,
                                     uint8_t rightPaddingNum, uint32_t srcGap, uint32_t dstGap)
    {
#ifdef USE_ASCENDC
        AscendC::DataCopyPad(dstTensor, srcTensor, AscendC::DataCopyExtParams(nBurst, lenBurst, srcGap, dstGap, 0));
#else
        if constexpr (sizeof(DType) == 1) {
            copy_ubuf_to_gm_align_b8((__gm__ DType *)dstTensor.GetPhyAddr(), (__ubuf__ DType *)srcTensor.GetPhyAddr(),
                                     sid, nBurst, lenBurst, leftPaddingNum, rightPaddingNum, srcGap, dstGap);
        } else if constexpr (sizeof(DType) == 2) {
            copy_ubuf_to_gm_align_b16((__gm__ DType *)dstTensor.GetPhyAddr(), (__ubuf__ DType *)srcTensor.GetPhyAddr(),
                                      sid, nBurst, lenBurst, leftPaddingNum, rightPaddingNum, srcGap, dstGap);
        } else if constexpr (sizeof(DType) == 4) {
            copy_ubuf_to_gm_align_b32((__gm__ DType *)dstTensor.GetPhyAddr(), (__ubuf__ DType *)srcTensor.GetPhyAddr(),
                                      sid, nBurst, lenBurst, leftPaddingNum, rightPaddingNum, srcGap, dstGap);
        }
#endif
    };
};